name: LSIF
on:
  - push
jobs:
  sourcegraph-index:
    runs-on: ubuntu-latest
    container: node:10.19.0-buster
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn kbn --allow-root bootstrap
      - name: Generate lsif data
        uses: sourcegraph/lsif-node-action@master
      - name: Upload LSIF data
        uses: sourcegraph/lsif-upload-action@master
        with:
          github_token: ${{ secrets.SRC_GITHUB_TOKEN }}
